

CREATE TABLE IF NOT EXISTS "trusted".M_CLIENTE
(
COD_PERSONATH	VARCHAR(100)
,TIP_PERSONA	VARCHAR(100)
,DES_TIPOPERSONA	VARCHAR(1000)
,TIP_DOCUMENTOIDENTIDAD	VARCHAR(100)
,DES_DOCUMENTOIDENTIDAD	VARCHAR(1000)
,FLG_DOCUMENTOIDENTIDAD	BOOLEAN
,FLG_RUC	BOOLEAN
,DES_NOMBRE	VARCHAR(1000)
,DES_APEPATERNO	VARCHAR(1000)
,DES_APEMATERNO	VARCHAR(1000)
,FEC_NACIMIENTO	TIMESTAMP
,CAN_EDAD	INTEGER
,TIP_SEXO	VARCHAR(100)
,TIP_ESTADOCIVIL	VARCHAR(100)
,FLG_TENENCIAHIJOS	BOOLEAN
,FLG_TELEFONOFIJO	BOOLEAN
,FLG_TELEFONOCELULAR	BOOLEAN
,FLG_CONSENTIMIENTOLLAMADA	BOOLEAN
,FLG_CORREO	BOOLEAN
,FLG_CONSENTIMIENTOEMAIL	BOOLEAN
,FLG_DIRECCION	BOOLEAN
,FLG_DIRECCIONERROR	BOOLEAN
,FLG_DIRECCIONGPS	BOOLEAN
,TIP_NIVELSOCIOECONOMICO	VARCHAR(100)
,FEC_AFILIACION	TIMESTAMP
,DES_AFILIACIONCADENA	VARCHAR(1000)
,FEC_CREACION	TIMESTAMP
,FEC_ULTIMAMODIFICACION	TIMESTAMP
,FLG_AUTORIZACOMPARTIRDATOSOCIO	BOOLEAN
,FLG_CLIENTEFALLECIDO	BOOLEAN
,FLG_AUTOCANJE	BOOLEAN

)


