

CREATE TABLE IF NOT EXISTS "trusted".M_PUNTOVENTA
(
COD_CADENA	VARCHAR(100)
,DES_PUNTOVENTA	VARCHAR(1000)
,COD_TIENDA	VARCHAR(100)
,DES_TIENDA	VARCHAR(1000)
,COD_DEPARTAMENTO	VARCHAR(100)
,COD_PROVINCIA	VARCHAR(100)
,COD_DISTRITO	VARCHAR(100)
,FLG_DIRECCIONGPS	BOOLEAN

)

