CREATE TABLE IF NOT EXISTS "trusted".M_TARJETA
(
COD_TARJETA	VARCHAR(100)
,COD_ESTADOTARJETA	VARCHAR(100)
,DES_ESTADOTARJETA	VARCHAR(1000)
,TIP_TARJETA	VARCHAR(100)
,DES_TIPTARJETA	VARCHAR(1000)
,COD_PERSONATH	VARCHAR(100)
,COD_PERSONA	VARCHAR(100)
,COD_CUENTA	VARCHAR(100)
,FEC_SOLICITUD	TIMESTAMP
,FEC_AFILIACION	TIMESTAMP
,DES_AFILIACIONCADENA	VARCHAR(1000)
,DES_AFILIACIONTIENDA	VARCHAR(1000)
,TIP_TARJETAFINANCIERA	VARCHAR(100)
,DES_AFILIACION	VARCHAR(1000)
)

