

CREATE TABLE IF NOT EXISTS "trusted".T_CANJE
(
COD_PERSONA	VARCHAR(100)
,COD_CUENTA	VARCHAR(100)
,DES_ESTACIONTRABAJO	VARCHAR(1000)
,TIP_CANJE	VARCHAR(100)
,NUM_TARJETA	BIGINT
,DES_CANJECADENA	VARCHAR(1000)
,DES_CANJETIENDA	VARCHAR(1000)
,FEC_TRANSACCION	TIMESTAMP
,FEH_TRANSACCION	TIMESTAMP
,DES_CAJA	VARCHAR(1000)
,NUM_SECUENCIA	BIGINT
,COD_CAJERACENCOSUD	VARCHAR(100)
,IMP_SOLESPAGADOS	DECIMAL(24,6)
,NUM_PUNTOSCANJEADOS	BIGINT
,NUM_PUNTOSANTESCANJE	BIGINT
,COD_PERSONATH	VARCHAR(100)
,DES_ESTADOCANJE	VARCHAR(1000)
,COD_CANJE	VARCHAR(100)

)

