


CREATE TABLE IF NOT EXISTS "trusted".T_DETALLECANJE
(
COD_CANJE	VARCHAR(100)
,ID_SECUUENCIAL	VARCHAR(100)
,COD_PRODUCTO	VARCHAR(100)
,DES_CANJE	VARCHAR(1000)
,DES_RUBRO	VARCHAR(1000)
,DES_CATEGORIA	VARCHAR(1000)
,DES_FAMILIA	VARCHAR(1000)
,COD_CAMPAÑA	VARCHAR(100)
,DES_CAMPAÑA	VARCHAR(1000)
,CAN_CANJE	INTEGER
,CAN_CANJEDEVUELTA	INTEGER
,NUM_PUNTOSPRODUCTO	BIGINT
,DES_SIGNO	VARCHAR(1000)
,IMP_PRECIOUNUTARIO	DECIMAL(24,6)
,COD_ALMACEN	VARCHAR(100)


)

