CREATE TABLE IF NOT EXISTS "trusted".T_RECLAMOS
(
COD_REGISTRO	VARCHAR(100)
,COD_PERSONATH	VARCHAR(100)
,NUM_TARJETA	BIGINT
,COD_RECLAMO	VARCHAR(100)
,DES_RECLAMO	VARCHAR(1000)
,COD_ESTADORECLAMO	VARCHAR(100)
,DES_ESTADORECLAMO	VARCHAR(1000)
,NOM_USUARIORECLAMO	VARCHAR(100)
,FEC_REGISTRORECLAMO	TIMESTAMP
,FEH_REGISTRORECLAMO	TIMESTAMP
,DES_REGISTRORECLAMOCADENA	VARCHAR(1000)
,DES_REGISTRORECLAMOTIENDA	VARCHAR(1000)
,NOM_USUARIOATENCION	VARCHAR(100)
,FEC_ATENCIONRECLAMO	TIMESTAMP
,FEH_ATENCIONRECLAMO	TIMESTAMP
,DES_ATENCIONRECLAMOCADENA	VARCHAR(1000)
,DES_ATENCIONRECLAMOTIENDA	VARCHAR(1000)


)


